# Generated by Django 5.0.4 on 2024-04-07 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tanks', 'Tanks'), ('healers', 'Healers'), ('dd', 'DD'), ('merchants', 'Merchants'), ('guildmasters', 'Guildmasters'), ('questgivers', 'Questgivers'), ('blacksmiths', 'Blacksmiths'), ('tanners', 'Tanners'), ('alchemists', 'Alchemists'), ('spell_masters', 'Spell Masters')], max_length=20, verbose_name='Category')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created data')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adverts', to=settings.AUTH_USER_MODEL, verbose_name='Author of the ad')),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Advert',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Reply text')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of response')),
                ('accept', models.BooleanField(default=False, verbose_name='Accept')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='callboard.advert', verbose_name='Advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Author of the ad')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'ordering': ['-response_date'],
            },
        ),
    ]
